name: CI My Profile Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # 1. pull code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Keep npm cache to speed up subsequent runs

      # 3. Install Dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests and build
      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build